import { useRef, useState } from 'react';
import { useScenarioStore } from '../../state/scenarioStore';
import { answerAssistant } from '../../assistant/assistantEngine';
import { Button } from '../common/Button';
import { AssistantMessage } from './AssistantMessage';
import { AssistantSuggestions } from './AssistantSuggestions';
import { Modal } from '../common/Modal';
import { generateBriefing } from '../../assistant/briefingGenerator';
import { copyAndOpen, type ExternalProvider } from '../../assistant/externalAI';
import { useFocusTrap } from '../accessibility/useFocusTrap';
export function AssistantDrawer({open,onClose}: {open:boolean;onClose:()=>void}){const scenario=useScenarioStore(s=>s.scenario);const [question,setQuestion]=useState('');const [answer,setAnswer]=useState('');const [briefProvider,setBriefProvider]=useState<ExternalProvider|null>(null);const ref=useRef<HTMLDivElement>(null);useFocusTrap(ref,open&&!briefProvider,onClose);if(!open)return null;const ask=(q:string)=>{setQuestion(q);setAnswer(answerAssistant(q,scenario));};const briefing=generateBriefing(scenario,'ministerial');return <><div className="drawer-backdrop" aria-hidden="true" onClick={onClose}/><aside ref={ref} className="drawer" role="dialog" aria-modal="true" aria-label="TAYA Policy Assistant" tabIndex={-1}><div className="controls-inline" style={{justifyContent:'space-between'}}><div><h2 style={{margin:0}}>TAYA Policy Assistant</h2><p className="small">Ask about the current scenario, calculations, assumptions or comparisons.</p></div><Button onClick={onClose}>Close</Button></div><AssistantSuggestions onSelect={ask}/>{answer&&<AssistantMessage text={answer}/>}<form onSubmit={e=>{e.preventDefault();ask(question);}}><div className="field"><label htmlFor="assistant-question">Question</label><textarea id="assistant-question" rows={3} value={question} onChange={e=>setQuestion(e.target.value)}/></div><Button className="primary" type="submit">Ask</Button></form><hr className="section-rule"/><h3>AI briefing</h3><p className="small">Generate the briefing locally, review the exact text, then copy it before opening an external service.</p><div className="action-row">{(['ChatGPT','Gemini','Copilot'] as ExternalProvider[]).map(p=><Button key={p} onClick={()=>setBriefProvider(p)}>Open in {p}</Button>)}</div></aside>{briefProvider&&<Modal title={`Open in ${briefProvider}`} onClose={()=>setBriefProvider(null)}><p><strong>No scenario data are sent automatically.</strong> Do not include personal, patient or confidential data.</p><textarea aria-label="External AI briefing text" rows={14} style={{width:'100%'}} readOnly value={briefing}/><div className="action-row"><Button className="primary" onClick={async()=>{await copyAndOpen(briefing,briefProvider);setBriefProvider(null);}}>Copy briefing and open</Button><Button onClick={()=>setBriefProvider(null)}>Cancel</Button></div></Modal>}</>}
