import type { Scenario } from '../types/scenario';
import { calculateUptake } from '../engine/uptake';
import { calculateReach } from '../engine/reach';
import { calculateCosts } from '../engine/costing';
import { calculateCapacity } from '../engine/capacity';
import { calculateEconomic } from '../engine/economic';
import { calculateEvidenceCoverage } from '../engine/evidenceCoverage';
import { evidenceRegistry } from '../data/evidenceRegistry';
import { oneWaySensitivity, thresholdForBcrOne } from '../engine/sensitivity';
import { formatCurrency } from '../utils/currency';
import { formatPercent } from '../utils/format';
import { generateLocalPolicyBrief } from './briefingGenerator';
function lower(s:string){return s.trim().toLowerCase();}
export function answerAssistant(question:string,s:Scenario):string{
  const q=lower(question);const u=calculateUptake(s);const r=calculateReach(s,u.family);const c=calculateCosts(s,r);const cap=calculateCapacity(s,r);const econ=calculateEconomic(s,r,c);
  if(/diagnos|symptom|my anxiety|clinical advice|treatment for me/.test(q))return 'TAYA-STEPS is a service-planning research tool and does not provide individual clinical advice. Use official Australian health information at healthdirect.gov.au for health information and service guidance.';
  if(q.includes('explain this scenario'))return `${s.name} starts in ${s.setting}, with a ${s.waitWeeks.toFixed(1)} week wait, ${s.delivery} delivery and ${s.professionalSupport} professional support. The prototype model estimates family-compatible uptake of ${formatPercent(u.family)}, producing about ${Math.round(r.starters).toLocaleString('en-AU')} starters from the current offered population.`;
  if(q.includes('driving uptake')){const entries=Object.entries(u.youthUtility).filter(([k])=>!['total','interactions'].includes(k)).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));return `For youth uptake, the largest absolute utility contribution is ${entries[0][0]} (${entries[0][1].toFixed(2)}). Waiting time contributes ${u.youthUtility.waitingTime.toFixed(2)} and family cost contributes ${u.youthUtility.cost.toFixed(2)}. Current prototype youth uptake is ${formatPercent(u.youth)}.`;}
  if(q.includes('youth uptake different')||q.includes('parent uptake different'))return `Youth uptake is ${formatPercent(u.youth)} and parent/carer uptake is ${formatPercent(u.parent)} because the prototype coefficient sets assign different values to setting, delivery, parent involvement, support intensity, waiting time and cost. These are synthetic literature-informed coefficients, not empirical dyadic TAYA estimates.`;
  if(q.includes('waiting time')){const changed=calculateUptake({...s,waitWeeks:s.waitWeeks+2});return `Increasing waiting time by 2 weeks changes prototype youth uptake from ${formatPercent(u.youth)} to ${formatPercent(changed.youth)} and parent/carer uptake from ${formatPercent(u.parent)} to ${formatPercent(changed.parent)}, holding other inputs constant.`;}
  if(q.includes('improve uptake'))return 'Under this prototype model, uptake can be improved by reducing waiting time and family cost and by selecting service features with more positive utility contributions. Use the contribution table to see which attributes are driving the current scenario.';
  if(q.includes('reduce cost'))return `Current annual service-provider resource cost is ${formatCurrency(c.annualTotalCost)}. Lower professional-contact intensity, lower loaded staff cost, fewer starters or lower fixed implementation costs reduce this total. These changes may also affect uptake and reach, so compare them jointly.`;
  if(q.includes('capacity exceeded')||q.includes('fte'))return `The current pathway requires ${cap.fteRequired.toFixed(2)} FTE against ${cap.fteAvailable.toFixed(2)} FTE available, with ${formatPercent(cap.utilisation)} utilisation. Status: ${cap.status}.`;
  if(q.includes('weakest assumptions')||q.includes('prototype assumptions')){const sens=oneWaySensitivity(s,'netBenefit').sort((a,b)=>Math.abs(b.high-b.low)-Math.abs(a.high-a.low));return `The current decision-sensitivity analysis identifies ${sens.slice(0,3).map(x=>x.parameter).join(', ')} as influential among the tested assumptions. The evidence register contains ${evidenceRegistry.filter(x=>x.sourceGrade==='D'&&x.usedInModel).length} active Grade D prototype assumptions.`;}
  if(q.includes('official data')||q.includes('official source')){const cov=calculateEvidenceCoverage(evidenceRegistry);return `${cov.counts.A} active model inputs are Grade A official Australian sources. Official contextual sources also include AIHW, eSafety, Healthdirect and Medicare Benefits Schedule references.`;}
  if(q.includes('break-even qaly'))return `The break-even QALY gain under current assumptions is ${econ.breakEvenQalyGain.toFixed(4)} QALYs per additional young person meaningfully improved.`;
  if(q.includes('bcr exceed')||q.includes('benefit-cost')){const t=thresholdForBcrOne(s);return `For the exploratory economic module to reach a benefit-cost ratio of 1 under the other current assumptions, the QALY gain would need to be about ${t.qalyGain.toFixed(4)}, or the incremental improvement probability about ${formatPercent(t.improvementProbability)}. These are threshold calculations, not evidence of cost-effectiveness.`;}
  if(q.includes('dce model'))return 'The prototype uses a binary logit model. Systematic utility is the alternative-specific constant plus utilities for setting, waiting time, delivery, parent involvement, professional support, follow-up and family cost, with optional subgroup modifiers. Uptake is logistic(V).';
  if(q.includes('budget impact'))return 'Budget impact multiplies modelled starters by pathway resource use and loaded staff costs, adds fixed costs, and applies annual nominal cost growth over the selected planning horizon. Ordinary budget totals are shown undiscounted.';
  if(q.includes('cost-benefit')||q.includes('economic'))return `The exploratory economic module estimates additional improved young people, QALY-related health value, avoided health-service expenditure and optional broader benefits, then subtracts intervention resource cost. Current exploratory BCR is ${econ.bcr.toFixed(2)}. It is not a TAYA effectiveness or cost-effectiveness estimate.`;
  if(q.includes('draft an executive brief')||q.includes('draft a service brief'))return generateLocalPolicyBrief(s);
  if(q.includes('regional'))return 'The regional/rural prototype modifier gives secure online access a small positive utility adjustment and increases waiting-time sensitivity by 10%. This is a Grade D prototype assumption and should be replaced by TAYA-specific evidence if available.';
  return `For the current scenario, family-compatible uptake is ${formatPercent(u.family)}, annual service-provider resource cost is ${formatCurrency(c.annualTotalCost)}, and workforce requirement is ${cap.fteRequired.toFixed(2)} FTE. Ask about uptake drivers, waiting time, cost, capacity, evidence, break-even values or the model methods.`;
}
