import { useScenarioStore } from '../state/scenarioStore';
import type { Scenario } from '../types/scenario';
import { calculateUptake } from '../engine/uptake';
import { calculateReach } from '../engine/reach';
import { calculateCosts } from '../engine/costing';
import { calculateEconomic } from '../engine/economic';
import { formatCurrency } from '../utils/currency';
import { formatPercent, formatNumber } from '../utils/format';
import { Button } from '../components/common/Button';
import { Alert } from '../components/common/Alert';
import { DataTable } from '../components/common/DataTable';
export function EconomicResults({scenario}: {scenario:Scenario}){const update=useScenarioStore(x=>x.updateScenario);if(!scenario.economicAcknowledged)return <section><h2>Exploratory economic value</h2><Alert kind="warning"><strong>These calculations use external effectiveness and valuation assumptions. They are exploratory scenario analyses, not estimates of TAYA effectiveness or cost-effectiveness.</strong></Alert><Button className="primary" onClick={()=>update({economicAcknowledged:true,economicEnabled:true})}>Acknowledge and open economic module</Button></section>;const u=calculateUptake(scenario),r=calculateReach(scenario,u.family),c=calculateCosts(scenario,r),e=calculateEconomic(scenario,r,c);const rows=[['Additional meaningfully improved',formatNumber(e.additionalImproved)],['Health value',formatCurrency(e.healthValue)],['Health-service offset',formatCurrency(e.healthServiceOffset)],['Broader benefit',formatCurrency(e.broaderBenefit)],['Total monetised benefit',formatCurrency(e.totalBenefit)],['Economic cost',formatCurrency(e.economicCost)],['Net benefit',formatCurrency(e.netBenefit)],['Benefit-cost ratio',e.bcr.toFixed(2)],['Break-even benefit per completer',formatCurrency(e.breakEvenBenefitPerCompleter)],['Break-even QALY gain',e.breakEvenQalyGain.toFixed(4)],['Break-even improvement probability',formatPercent(e.breakEvenImprovementProbability)]].map(([m,v])=>({m,v}));return <section><h2>Exploratory economic value</h2><Alert kind="warning">These are exploratory scenario analyses, not estimates of TAYA effectiveness or cost-effectiveness. The value per QALY is an illustrative scenario value and is not presented as an official Australian decision threshold.</Alert><p><strong>Headline result:</strong> exploratory net benefit is {formatCurrency(e.netBenefit)} and BCR is {e.bcr.toFixed(2)} under the current assumptions.</p><DataTable caption="Exploratory economic value results" rows={rows} columns={[{key:'m',header:'Measure',render:r=>r.m},{key:'v',header:'Value',render:r=>r.v}]}/></section>;}
