import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register';
import App from './app/App';
import './styles/tokens.css';
import './styles/reset.css';
import './styles/global.css';
import './styles/layout.css';
import './styles/components.css';
import './styles/print.css';
registerSW({immediate:true,onOfflineReady(){console.info('TAYA-STEPS is ready for offline use.');}});
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
